# Generated by Django 4.1.9 on 2024-09-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContaEnergia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_conta", models.CharField(max_length=100, unique=True)),
                ("consumo_kwh", models.FloatField()),
                ("pegada_de_carbono", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
